routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\Admin\AdminArticleController;
use App\Http\Controllers\Admin\AdminCategoryController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminFeedbackController;
use App\Http\Controllers\Admin\AdminImageController;
use App\Http\Controllers\Api\ApiImagesController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DifferentController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\TravelController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/portfolio', [PortfolioController::class, 'portfolio'])->name('portfolio');
Route::get('/category/{id}', [CategoryController::class, 'oneCategory'])->name('category');
Route::get('/article/{id}', [ArticleController::class, 'oneArticle'])->name('article');
Route::get('/about', [AboutController::class, 'about'])->name('about');
Route::resource('feedback', FeedbackController::class);

Route::middleware('role:admin')
    ->prefix('admin')
    ->group(function () {
        Route::resource('/article', AdminArticleController::class);
        Route::resource('/category', AdminCategoryController::class);
        Route::resource('/images', AdminImageController::class);
        Route::resource('/reviews', AdminFeedbackController::class);

        Route::get('/index', [AdminController::class, 'index'])->name('home_admin');
        Route::get('/articles', [AdminController::class, 'article'])->name('article_admin');
        Route::get('/categories', [AdminController::class, 'category'])->name('category_admin');

    });
//Route::group(['as' => 'api.', 'prefix' => 'api'], function () {
//    Route::get('/apiImages/id', [ApiImagesController::class, 'index']);
//});

Route::get('api/apiImages/{id}', [ApiImagesController::class, 'index']);

require __DIR__ . '/auth.php';

resources/views/admin/addImage.blade.php
@extends('layouts.app')

@section('content')

    <main class="main">

        <div class="admin-performance">
            <div class="admin-performance__block container">
                <h2>Страница администратора</h2>
                <h3>Добавление фотографии</h3>
            </div>
        </div>

        <div class="block-form container">
            <form method="POST" enctype="multipart/form-data"
                  action="{{ route('images.store') }}">
                @csrf


{{--                <input name="title" type="text"--}}
{{--                       class="block-form__input @error('title') block-form__input_error @enderror"--}}
{{--                       placeholder="Заголовок статьи">--}}

{{--                @error('title')--}}
{{--                <p class="block-form__text-error">{{ $message }}</p>--}}
{{--                @enderror--}}

                <select class="block-form__input" name="article_id">
                    <option disabled>надо выбрать статью</option>
                    @foreach($articles as $article)
                        <option value="{{$article->id}}">{{$article->title}}</option>
                    @endforeach
                </select>



                <input name="description" type="text"
                       class="block-form__input @error('description') block-form__input_error @enderror"
                       placeholder="Короткое описание фотографии"/>

                @error('description')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror


                <input class="block-form__input" type="file" name="name_image">

                <button class="button admin__button" type="submit"
                        value="save">
                    Сохранить
                </button>
            </form>

            <a class="button admin__button" href="{{route('article_admin')}}">
                <span class="transition-button__text">Назад</span>
            </a>

        </div>

    </main>
@endsection

{{--@push('scripts')--}}
{{--    <script>--}}

{{--        ClassicEditor--}}
{{--            .create(document.querySelector('#editor'))--}}
{{--            .catch(error => {--}}
{{--                console.error(error);--}}
{{--            });--}}

{{--    </script>--}}
{{--@endpush--}}

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')

    <main class="main">

        <div class="admin-performance">
            <div class="admin-performance__block container">
                <h2>Страница администратора</h2>
                <h3>{{$name_page}}</h3>
            </div>
        </div>

        <div class="admin-main container">

            <nav class="admin-nav">
                <a class="admin-nav__text" href="{{route('home_admin')}}"> Обращения </a>
                <a class="admin-nav__text" href="{{route('article_admin')}}"> Статьи </a>
                <a class="admin-nav__text" href="{{route('category_admin')}}"> Разделы </a>
            </nav>

            <table class="admin-table">
                <thead>
                <tr>
                    <th class="admin-table__content">Содержание</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>

                @foreach ($array_data as $data)
                    <tr>
                        <td>{{ $data->message??$data->description??$data->title}}</td>
                        <td class="admin-table__block-button">

                            <a class="button admin-table__button" href="{{route($action_button, $data)}}">
                                {{$button_name}}
                            </a>

                            <form action="{{route($delete_button, $data)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="button admin-table__button" type="submit">Удалить</button>
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>

            {{ $array_data->links() }}

            @isset($add_button)
                <div class="button admin__button">
                    <a class="admin__button_text" href="{{$add_elem}}">
                        {{$add_button}}
                    </a>
                </div>
            @endisset

            @isset($image_button)
                <div class="button admin__button">
                    <a class="admin__button_text" href="{{route('images.create')}}">
                        {{$image_button}}
                    </a>
                </div>
            @endisset

        </div>

    </main>

@endsection

resources/views/admin/newArticle.blade.php
@extends('layouts.app')

@section('content')

    <main class="main">

        <div class="admin-performance">
            <div class="admin-performance__block container">
                <h2>Страница администратора</h2>
                <h3>  {{ isset($article) ? ('Редактирование статьи:' . ' ' . $article->title) :  ('Создание новой статьи') }}</h3>
            </div>
        </div>

        <div class="block-form container">
            <form method="POST" enctype="multipart/form-data"
                  action="{{ isset($article) ? route('article.update', $article) : route('article.store') }}">
                @csrf

                @if(isset($article))
                    @method('PUT')
                @endif

                @if(is_int($category))
                    <input type="hidden" name="category_id" value="{{$category}}">
                @else
                    <select class="block-form__input" name="category_id">
                        <option disabled>надо выбрать категорию</option>
                        @foreach($category as $item)
                            <option value="{{$item->id}}">{{$item->title}}</option>
                        @endforeach
                    </select>

                @endif

                <input name="title" type="text"
                       class="block-form__input @error('title') block-form__input_error @enderror"
                       placeholder="Заголовок статьи" value="{{ $article->title ?? '' }}"/>

                @error('title')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror

                <input name="description" type="text"
                       class="block-form__input @error('description') block-form__input_error @enderror"
                       placeholder="Короткое описание статьи"
                       value="{{ $article->description ?? '' }}"/>

                @error('description')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror

                <textarea id="editor" name="articles_body"
                          class="block-form__input @error('articles_body') block-form__input_error @enderror"
                          placeholder="текст статьи"
                >{{ $article->articles_body ?? '' }}</textarea>

                @error('articles_body')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror

                <button class="button admin__button" type="submit"
                        value="save">
                    Сохранить
                </button>
            </form>

            <a class="button admin__button" href="{{route('article_admin')}}">
                <span class="transition-button__text">Назад</span>
            </a>

        </div>

    </main>
@endsection

@push('scripts')
    <script>

        ClassicEditor
            .create(document.querySelector('#editor'))
            .catch(error => {
                console.error(error);
            });

    </script>
@endpush

resources/views/admin/newCategory.blade.php
@extends('layouts.app')

@section('content')

    <main class="main">

        <div class="admin-performance">
            <div class="admin-performance__block container">
                <h2>Страница администратора</h2>
                <h3>  {{ isset($category) ? ('Редактирование раздела:' . ' ' . $category->title) :  ('Создание нового раздела') }}</h3>
            </div>
        </div>

        <div class="block-form container">

            <form method="POST"
                  action="{{ isset($category) ? route('category.update', $category) : route('category.store') }}">
                @csrf

                @if(isset($category))
                    @method('PUT')
                @endif

                <input name="title" type="text"
                       class="block-form__input @error('title') block-form__input_error @enderror"
                       placeholder="Заголовок статьи" value="{{ $category->title ?? '' }}"/>

                @error('title')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror

                <button type="submit" class="button admin__button"
                        value="save">
                    Сохранить
                </button>
            </form>

            <a class="button admin__button" href="{{route('category_admin')}}">
                <span class="transition-button__text">Назад</span>
            </a>
        </div>

    </main>

@endsection

resources/views/admin/oneArticle.blade.php
@extends('layouts.app')

@section('content')

    <main class="main">

        <div class="admin-performance">
            <div class="admin-performance__block container">
                <h2>Страница администратора</h2>
                <h3>Просмотр статьи {{ $article->title }}</h3>
            </div>
        </div>

        <div class="container">

            <p> Фотографии статьи: </p>
            <div class="presentation container wrapper">
                @isset($images)
                    @foreach($images as $image)
                        <div class="presentation__item">
                            <img class="presentation__photo" src="/storage/images/{{$image->name_image}}" alt="photo">
                            <div class="presentation__hover">
                                    <h3>{{$image->description}}</h3>
                            </div>
                        </div>
                    @endforeach
                @endisset
            </div>

            <h2>Заголовок статьи: {{ $article->title }}</h2>
            <h3>Описание статьи: {{ $article->description }}</h3>
            <p> Текст статьи: </p>
            {!! $article->articles_body !!}

            <form action="{{route('article.edit', $article)}}" method="GET">
                @csrf
                <button class="button admin__button" type="submit">
                    <span class="transition-button__text">Перейти к редактированию статьи</span>
                </button>
            </form>

            <form action="{{route('images.create')}}" method="GET">
                @csrf
                <button class="button admin__button" type="submit">
                    <span class="transition-button__text">Перейти к добавлению фотографии</span>
                </button>
            </form>

            <form action="{{route('article.destroy', $article)}}" method="POST">
                @csrf
                @method('DELETE')
                <button class="button admin__button" type="submit">
                    <span class="transition-button__text">Удалить статью</span>
                </button>
            </form>

            <a class="button admin__button" href="{{route('article.create')}}">
                <span class="transition-button__text">Создать еще одну статью</span>
            </a>

            <a class="button admin__button" href="{{route('article_admin')}}">
                <span class="transition-button__text">Назад на главную страницу</span>
            </a>
        </div>

    </main>

@endsection

resources/views/admin/oneFeedback.blade.php
@extends('layouts.app')

@section('content')

    <main class="main">

        <div class="admin-performance">
            <div class="admin-performance__block container">
                <h2>Страница администратора</h2>
                <h3>Просмотр отзыва {{ $feedback->name }}</h3>
            </div>
        </div>

        <div class="container">

            <h2>Обратился: {{ $feedback->name }}</h2>
            <h3>Электронная почта: {{ $feedback->email }}</h3>
            <h3>Телефон: {{ $feedback->phone }}</h3>
            <p>Текст обращения: {{ $feedback->message }}</p>

            <a class="button admin__button" href="{{route('home_admin')}}">
                <span class="transition-button__text">Назад</span>
            </a>
        </div>

    </main>
@endsection